// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2HhQJAraXM2ykl2uQ_938ZxZxvvl-kHA',
    appId: '1:738356872374:web:1f32fe5ed60a667dd7d217',
    messagingSenderId: '738356872374',
    projectId: 'event-manager-55e57',
    authDomain: 'event-manager-55e57.firebaseapp.com',
    storageBucket: 'event-manager-55e57.appspot.com',
    measurementId: 'G-9XKN8WDDNB',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALksN_YyegBbMe-jIaOIHvp6g92VSYIoU',
    appId: '1:738356872374:ios:8faf8fd3794671d2d7d217',
    messagingSenderId: '738356872374',
    projectId: 'event-manager-55e57',
    storageBucket: 'event-manager-55e57.appspot.com',
    iosBundleId: 'com.example.eventsManage',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB2HhQJAraXM2ykl2uQ_938ZxZxvvl-kHA',
    appId: '1:738356872374:web:ea6261b5b2e337cad7d217',
    messagingSenderId: '738356872374',
    projectId: 'event-manager-55e57',
    authDomain: 'event-manager-55e57.firebaseapp.com',
    storageBucket: 'event-manager-55e57.appspot.com',
    measurementId: 'G-7Q4ZSPYM4J',
  );

}